# Generated by Django 4.1.3 on 2022-11-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pattern_display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_image', models.ImageField(upload_to='pattern_images')),
                ('pattern_description', models.CharField(max_length=100)),
            ],
        ),
    ]
