# Generated by Django 4.1.3 on 2022-11-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_pattern_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='accessories_display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_image', models.ImageField(upload_to='accesories_images')),
                ('accessories_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='costumes_display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costumes_image', models.ImageField(upload_to='costume_images')),
                ('costumes_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ornaments_display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_image', models.ImageField(upload_to='ornaments_images')),
                ('ornaments_description', models.CharField(max_length=100)),
            ],
        ),
    ]
