# Generated by Django 4.1.3 on 2022-11-30 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_accessories_display_costumes_display_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessories_display',
            old_name='pattern_image',
            new_name='accessories_image',
        ),
        migrations.RenameField(
            model_name='ornaments_display',
            old_name='pattern_image',
            new_name='ornamnets_image',
        ),
    ]
