# Generated by Django 4.1.3 on 2022-11-30 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_rename_pattern_image_accessories_display_accessories_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='costumes_display',
        ),
    ]
