# Generated by Django 4.1.3 on 2022-11-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_delete_costumes_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ornaments_display',
            old_name='ornamnets_image',
            new_name='ornaments_image',
        ),
    ]
