# Generated by Django 4.1.3 on 2022-12-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_pattern_display_pattern_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories_display',
            name='accessories_detail',
            field=models.CharField(default='accessories detailed description here', max_length=200),
        ),
    ]
