# Generated by Django 4.1.3 on 2022-12-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_accessories_display_accessories_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=100),
        ),
    ]
